fix: incorrect workflow config

diff --git a/.github/workflows/test-plan.yaml b/.github/workflows/test-plan.yaml
--- a/.github/workflows/test-plan.yaml
+++ b/.github/workflows/test-plan.yaml
@@ -75,14 +75,28 @@ jobs:
             exit 1
           fi
 
-          cat '${{ steps.plan.outputs.json_plan_path }}'
-          if [[ $(jq -r .format_version "${{ steps.plan.outputs.json_plan_path }}") != "1.1" ]]; then
-            echo "::error:: json_plan_path not set correctly"
+          if [[ -n "${{ steps.plan.outputs.json_plan_path }}" ]]; then
+            echo "::error:: json_plan_path should not be set - not available with terraform 11"
             exit 1
           fi
 
-          if ! grep -q "No changes" '${{ steps.plan.outputs.text_plan_path }}'; then
+          if ! grep -q "Terraform will perform the following actions" '${{ steps.plan.outputs.text_plan_path }}'; then
             echo "::error:: text_plan_path not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_add }} -ne 1 ]]; then
+            echo "::error:: to_add not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_change }} -ne 0 ]]; then
+            echo "::error:: to_change not set correctly"
+            exit 1
+          fi
+
+          if [[ ${{ steps.plan.outputs.to_destroy }} -ne 0 ]]; then
+            echo "::error:: to_destroy not set correctly"
             exit 1
           fi
 
