fix: check if plan too long for pr comment

diff --git a/.github/workflows/test-plan.yaml b/.github/workflows/test-plan.yaml
--- a/.github/workflows/test-plan.yaml
+++ b/.github/workflows/test-plan.yaml
@@ -50,6 +50,52 @@ jobs:
           echo "if expression should not have evaluated true"
           exit 1
 
+  too_long:
+    runs-on: ubuntu-latest
+    name: Plan too long
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Plan
+        uses: ./terraform-plan
+        id: plan
+        with:
+          path: tests/workflows/test-plan/too_long
+
+      - name: Verify outputs
+        run: |
+          echo "changes=${{ steps.plan.outputs.changes }}"
+
+          if [[ "${{ steps.plan.outputs.changes }}" != "false" ]]; then
+            echo "::error:: output changes not set correctly"
+            exit 1
+          fi
+
+          cat '${{ steps.plan.outputs.json_plan_path }}'
+          if [[ $(jq -r .format_version "${{ steps.plan.outputs.json_plan_path }}") != "1.1" ]]; then
+            echo "::error:: json_plan_path not set correctly"
+            exit 1
+          fi
+
+          if ! grep -q "No changes" '${{ steps.plan.outputs.text_plan_path }}'; then
+            echo "::error:: text_plan_path not set correctly"
+            exit 1
+          fi
+
+          if [[ -n "${{ steps.apply.outputs.run_id }}" ]]; then
+            echo "::error:: run_id should not be set"
+            exit 1
+          fi
+
+      - name: Test output expressions
+        if: steps.plan.outputs.to_add != 0 || steps.plan.outputs.to_change != 0 || steps.plan.outputs.to_destroy != 0
+        run: |
+          echo "if expression should not have evaluated true"
+          exit 1
+
   no_changes_no_comment:
     runs-on: ubuntu-latest
     name: No changes without comment
